### ISSUE TITLE
As a User, I want to come to homepage and understand what the website is for

### ISSUE THREAD

**Issue by jamiecoe** [FACN7/the-experts#1]
As a User, I want to come to homepage and understand what the website is for.

- [x] Make a home page with a description of website (including an image)  #4 
- [x] Research connecting React & Express #5 
- [x] Serve the home page on the `/` route #6
