### ISSUE TITLE
As a User, I want to create an account

### ISSUE THREAD

**Issue by ebraheemabbas** [FACN7/the-experts#43]
As a User, I want to create an account
- [x] Sign-up/sign-in pages #53
- [x] Add users table #46
- [x] BE authentication #58 && #59 
- [x] Login/Logout nav-bar functionality #61
